config/routes.rb
Slices::Application.routes.draw do
  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # creates about_path
  get "howitworks" => "pages#howitworks"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def howitworks
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<div class="container">
<nav class="navbar navbar navbar-default" role="navigation">

  <div class="container-fluid">

      <!-- Brand and toggle get grouped for better mobile display -->
   <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
       </button> 
         <%= link_to "Over", root_path, class: "navbar-brand" %>
          
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %> </li>
        <li><%= link_to "About Us", about_path %> </li>
        <li><%= link_to "How It Works", howitworks_path %> </li>

        <% if user_signed_in? %>
          <li> <%= link_to "My Settings", edit_user_registration_path %> </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %> </li>

        <% else %>
          <li><%= link_to "Log in", new_user_session_path %> </li>
          
        <% end %>




            
       </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slices</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name= "viewport" content="width-device-width, initial-scale=1.0>"
</head>

<body>

  <%= render 'layouts/header'%>	

  <% flash.each do |name, msg| %>
  	<%= content_tag(:div, msg, class: "alert alert-info") %>


   <% end %>
   
  <%= yield %>
  </div>

</body>

</html>

app/views/pages/about.html.erb
<div class="jumbotron" style="text-align:center;line-height:1.4;">

	<h1 style="text-align:center;font-weight:bold;color:#8d78dd;">Text 540-555-5555</h1>



	<h2 style="margin-bottom:100px;font-size:32px;font-weight:400;">order a meal or desert from <br>a neighbor or someone near you - no restaunts! </h2>

	

	

	<div style="margin:0; padding:0;width:100%;">
		<div style="margin:0 auto; width:1000px;">
			<h3 style="font-weight:700; font-size:32px;">How This Works</h3>
			<p style="font-weight:normal;line-height:1.4;font-size:22px;">You text what you want to eat. The <span style="color:#8d78dd;font-weight:bold;"> Over</span> team messages vetted hosts in your community to find out who is making food similar to what you want or is willing to eat or make something similar for the today. Once a match is found, we notify you and then collect a payment. The next step is to arrange a time and place to meet your host(ess) and get your meal... and you're done - that simple! </p>


		</div>
		<div class="background">
			<h3 style="font-weight:700; font-size:32px;">Background</h3>
			<p style="font-weight:normal;line-height:1.4;font-size:22px;">I've been self-employed for most of my adult life and naturally that means working long hours, as many other entrepreneurs know all too well. And I've always been athletic and health conscous but at least 5 out days in a week I would eat out order take-out because I would get home and keep working or use the time rest before the next day started. After years of this in different ventures, I thought... what if my neighbors preping my meals and I just paid them instead of 

			at work and going home to keep working or take care of important stuff, I found myself having to order takeout food most of the days in a week, probably 5 or of 7 days I would eat out. 
			</p>

		</div>

		<div class="questions">
			<h3 style="font-weight:700; font-size:32px;">Qs & As</h3>
			<h4 style="font-size:22;color:#222; text-transform:uppercase;">will my food be warm?</h4>
			<p style="font-weight:normal;line-height:1.4;font-size:22px;color:#666;">absolutely. Your host or hostess will package the meal in an approved  <span style="color:#8d78dd;font-weight:bold;"> Over</span> container that will keep your meal warm for a few hours</p> 

			<h4 style="font-size:22;color:#222; text-transform:uppercase;">How do i become a host or hostess? </h4>
			<p  style="font-weight:normal;line-height:1.4;font-size:22px;color:#666;">
				Email <a style="color:#3cc;" href="mailto:hosting@getoverlab.com">hosting@getoverlabs.com </a> and let us know why you wanna join and what experience do you have in the kitchen - please be specific!




			</p>

		</div>


	</div>
	<footer style="border-top:1px solid lightgray;padding:15px 0;">
		<div>Over is a service provided by Over Labs, Inc., based in Blacksburg, Virginia.</div><br>

		<div>
			<ul>
				<li style="display:block;">Over Labs, Inc.</li>
				<li style="display:block;">2200 Kraft Drive Suite 2525</li>
				<li style="display:block;">Blacksburg, VA 24060.</li>
			</ul>
		</div>

		<div >
			<ul style="display:block;">
				<h4>Get in touch</h4>
				<li style="display:block;"><a style="color:black;" href="mailto:hello@getoverlabs.com">Email us</a> </li>
				or
				<li style="display:block;"><a style="color:black;" href="/">Facebook</a></li>

			</ul>
		</div>
	</footer>
</div>
	

app/views/pages/home.html.erb
<div class="jumbotron center">
	
	<h1>Delicious Desserts</h1>
	<h3>We're a marketplace that connects dessert lovers bakers for fresh and delicious treats.</h3>

	<% if user_signed_in? %>
		#do something
	<% else %>

		<p> 
			<%= link_to "Log in", new_user_session_path,  class:"btn btn-default btn-lg" %> or 
			<%= link_to "Sign up", new_user_registration_path,  class:"btn btn-primary btn-lg" %> for beta.
		</p>
	<% end %>
	
</div>

app/views/pages/howitworks.html.erb
 <div class="jumbotron">
 	 <h1>How It Works!</h1>
 	 	<h5>We're creating a marketplace for people to enjoy homemade treats and deserts from local bakers, all made with organic products.</h5>
 	 	
		<h3>1. Create an account </h3>
		<h3>2. Choose from a large selection of delicious sweets or tell us what you want </h3>
		<h3>3. Tell us when and where to deliver </h3>
		<h3>That's it. Three easy steps. Join he movement! </h3>

  	<p><a class="btn btn-primary btn-lg" role="button">Sign up</a></p>
	</div>
</div>
